// Code generated by goctl. DO NOT EDIT.
// Source: user_server.proto

package userpermissions

import (
	"context"

	"user_server/user_server"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolRespVo                 = user_server.BoolRespVo
	CreatePermissionReqVo      = user_server.CreatePermissionReqVo
	CreateRoleReqVo            = user_server.CreateRoleReqVo
	CreateUserReqVo            = user_server.CreateUserReqVo
	Empty                      = user_server.Empty
	JwtTokenRespVo             = user_server.JwtTokenRespVo
	PermissionIdReqVo          = user_server.PermissionIdReqVo
	PermissionInfoRespVo       = user_server.PermissionInfoRespVo
	PermissionNameReqVo        = user_server.PermissionNameReqVo
	PermissionRolesRespVo      = user_server.PermissionRolesRespVo
	RoleIdPermissionIdReqVo    = user_server.RoleIdPermissionIdReqVo
	RoleIdReqVo                = user_server.RoleIdReqVo
	RoleInfoListRespVo         = user_server.RoleInfoListRespVo
	RoleInfoRespVo             = user_server.RoleInfoRespVo
	RolePermissionReqVo        = user_server.RolePermissionReqVo
	RolePermissionRespVo       = user_server.RolePermissionRespVo
	RolePermissionsRespVo      = user_server.RolePermissionsRespVo
	RoleUsersRespVo            = user_server.RoleUsersRespVo
	UpdateUserReqVo            = user_server.UpdateUserReqVo
	UserIdReqVo                = user_server.UserIdReqVo
	UserInfoRespVo             = user_server.UserInfoRespVo
	UserRoleReqVo              = user_server.UserRoleReqVo
	UserRoleRespVo             = user_server.UserRoleRespVo
	UserRolesRespVo            = user_server.UserRolesRespVo
	UserTokenPermissionIdReqVo = user_server.UserTokenPermissionIdReqVo
	VerificationReqVo          = user_server.VerificationReqVo

	UserPermissions interface {
		// 检查用户是否具有某权限
		UserHasPermission(ctx context.Context, in *UserTokenPermissionIdReqVo, opts ...grpc.CallOption) (*BoolRespVo, error)
	}

	defaultUserPermissions struct {
		cli zrpc.Client
	}
)

func NewUserPermissions(cli zrpc.Client) UserPermissions {
	return &defaultUserPermissions{
		cli: cli,
	}
}

// 检查用户是否具有某权限
func (m *defaultUserPermissions) UserHasPermission(ctx context.Context, in *UserTokenPermissionIdReqVo, opts ...grpc.CallOption) (*BoolRespVo, error) {
	client := user_server.NewUserPermissionsClient(m.cli.Conn())
	return client.UserHasPermission(ctx, in, opts...)
}
