// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: api/user_server.proto

package user_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户ID请求消息
type UserIdReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID
}

func (x *UserIdReqVo) Reset() {
	*x = UserIdReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIdReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdReqVo) ProtoMessage() {}

func (x *UserIdReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdReqVo.ProtoReflect.Descriptor instead.
func (*UserIdReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{0}
}

func (x *UserIdReqVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 创建用户请求消息
type CreateUserReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // 用户名
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`       // 用户邮箱
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // 用户密码
}

func (x *CreateUserReqVo) Reset() {
	*x = CreateUserReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReqVo) ProtoMessage() {}

func (x *CreateUserReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReqVo.ProtoReflect.Descriptor instead.
func (*CreateUserReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReqVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserReqVo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReqVo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 更新用户请求消息
type UpdateUserReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewName  string `protobuf:"bytes,1,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"` // 新用户名
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                    // 用户邮箱
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`              // 用户密码
}

func (x *UpdateUserReqVo) Reset() {
	*x = UpdateUserReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReqVo) ProtoMessage() {}

func (x *UpdateUserReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReqVo.ProtoReflect.Descriptor instead.
func (*UpdateUserReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserReqVo) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *UpdateUserReqVo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserReqVo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 验证请求消息（用于登录和删除用户）
type VerificationReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // 用户邮箱
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 用户密码
}

func (x *VerificationReqVo) Reset() {
	*x = VerificationReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationReqVo) ProtoMessage() {}

func (x *VerificationReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationReqVo.ProtoReflect.Descriptor instead.
func (*VerificationReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationReqVo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerificationReqVo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 角色ID请求消息
type RoleIdReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 角色ID
}

func (x *RoleIdReqVo) Reset() {
	*x = RoleIdReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleIdReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleIdReqVo) ProtoMessage() {}

func (x *RoleIdReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleIdReqVo.ProtoReflect.Descriptor instead.
func (*RoleIdReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{4}
}

func (x *RoleIdReqVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 创建角色请求消息
type CreateRoleReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 角色名
}

func (x *CreateRoleReqVo) Reset() {
	*x = CreateRoleReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoleReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReqVo) ProtoMessage() {}

func (x *CreateRoleReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReqVo.ProtoReflect.Descriptor instead.
func (*CreateRoleReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoleReqVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 用户角色请求消息
type UserRoleReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	RoleId int64 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 角色ID
}

func (x *UserRoleReqVo) Reset() {
	*x = UserRoleReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRoleReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleReqVo) ProtoMessage() {}

func (x *UserRoleReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleReqVo.ProtoReflect.Descriptor instead.
func (*UserRoleReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{6}
}

func (x *UserRoleReqVo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRoleReqVo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 角色权限请求消息
type RolePermissionReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId       int64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                   // 角色ID
	PermissionId int64 `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"` // 权限ID
}

func (x *RolePermissionReqVo) Reset() {
	*x = RolePermissionReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePermissionReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionReqVo) ProtoMessage() {}

func (x *RolePermissionReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionReqVo.ProtoReflect.Descriptor instead.
func (*RolePermissionReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{7}
}

func (x *RolePermissionReqVo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RolePermissionReqVo) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

// 权限ID请求消息
type PermissionIdReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 权限ID
}

func (x *PermissionIdReqVo) Reset() {
	*x = PermissionIdReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionIdReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionIdReqVo) ProtoMessage() {}

func (x *PermissionIdReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionIdReqVo.ProtoReflect.Descriptor instead.
func (*PermissionIdReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{8}
}

func (x *PermissionIdReqVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 创建权限请求消息
type CreatePermissionReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 权限名
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 权限描述
}

func (x *CreatePermissionReqVo) Reset() {
	*x = CreatePermissionReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePermissionReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionReqVo) ProtoMessage() {}

func (x *CreatePermissionReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionReqVo.ProtoReflect.Descriptor instead.
func (*CreatePermissionReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePermissionReqVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionReqVo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 角色ID和权限ID请求消息
type RoleIdPermissionIdReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId       int64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                   // 角色ID
	PermissionId int64 `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"` // 权限ID
}

func (x *RoleIdPermissionIdReqVo) Reset() {
	*x = RoleIdPermissionIdReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleIdPermissionIdReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleIdPermissionIdReqVo) ProtoMessage() {}

func (x *RoleIdPermissionIdReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleIdPermissionIdReqVo.ProtoReflect.Descriptor instead.
func (*RoleIdPermissionIdReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{10}
}

func (x *RoleIdPermissionIdReqVo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleIdPermissionIdReqVo) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

// 用户Token和权限ID请求消息
type UserTokenPermissionIdReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token          string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                         // JWT Token
	PermissionName string `protobuf:"bytes,2,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"` // 权限名称
}

func (x *UserTokenPermissionIdReqVo) Reset() {
	*x = UserTokenPermissionIdReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTokenPermissionIdReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTokenPermissionIdReqVo) ProtoMessage() {}

func (x *UserTokenPermissionIdReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTokenPermissionIdReqVo.ProtoReflect.Descriptor instead.
func (*UserTokenPermissionIdReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{11}
}

func (x *UserTokenPermissionIdReqVo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserTokenPermissionIdReqVo) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

// 权限名称请求消息
type PermissionNameReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PermissionNameReqVo) Reset() {
	*x = PermissionNameReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionNameReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionNameReqVo) ProtoMessage() {}

func (x *PermissionNameReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionNameReqVo.ProtoReflect.Descriptor instead.
func (*PermissionNameReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{12}
}

func (x *PermissionNameReqVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 用户信息响应消息
type UserInfoRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // 用户ID
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // 用户名
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // 用户邮箱
}

func (x *UserInfoRespVo) Reset() {
	*x = UserInfoRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRespVo) ProtoMessage() {}

func (x *UserInfoRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRespVo.ProtoReflect.Descriptor instead.
func (*UserInfoRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{13}
}

func (x *UserInfoRespVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoRespVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoRespVo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// JWT Token响应消息
type JwtTokenRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT Token
}

func (x *JwtTokenRespVo) Reset() {
	*x = JwtTokenRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtTokenRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtTokenRespVo) ProtoMessage() {}

func (x *JwtTokenRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtTokenRespVo.ProtoReflect.Descriptor instead.
func (*JwtTokenRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{14}
}

func (x *JwtTokenRespVo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 角色信息响应消息
type RoleInfoRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 角色ID
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 角色名
}

func (x *RoleInfoRespVo) Reset() {
	*x = RoleInfoRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfoRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfoRespVo) ProtoMessage() {}

func (x *RoleInfoRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfoRespVo.ProtoReflect.Descriptor instead.
func (*RoleInfoRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{15}
}

func (x *RoleInfoRespVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfoRespVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 角色信息列表响应消息
type RoleInfoListRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleList []*RoleInfoRespVo `protobuf:"bytes,1,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"` // 角色信息列表
}

func (x *RoleInfoListRespVo) Reset() {
	*x = RoleInfoListRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfoListRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfoListRespVo) ProtoMessage() {}

func (x *RoleInfoListRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfoListRespVo.ProtoReflect.Descriptor instead.
func (*RoleInfoListRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{16}
}

func (x *RoleInfoListRespVo) GetRoleList() []*RoleInfoRespVo {
	if x != nil {
		return x.RoleList
	}
	return nil
}

// 用户角色响应消息
type UserRoleRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	RoleId int64 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 角色ID
}

func (x *UserRoleRespVo) Reset() {
	*x = UserRoleRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRoleRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleRespVo) ProtoMessage() {}

func (x *UserRoleRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleRespVo.ProtoReflect.Descriptor instead.
func (*UserRoleRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{17}
}

func (x *UserRoleRespVo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRoleRespVo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 用户角色列表响应消息
type UserRolesRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []*RoleInfoRespVo `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"` // 角色信息列表
}

func (x *UserRolesRespVo) Reset() {
	*x = UserRolesRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRolesRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRolesRespVo) ProtoMessage() {}

func (x *UserRolesRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRolesRespVo.ProtoReflect.Descriptor instead.
func (*UserRolesRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{18}
}

func (x *UserRolesRespVo) GetRoles() []*RoleInfoRespVo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 角色用户列表响应消息
type RoleUsersRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*UserInfoRespVo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // 用户信息列表
}

func (x *RoleUsersRespVo) Reset() {
	*x = RoleUsersRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleUsersRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUsersRespVo) ProtoMessage() {}

func (x *RoleUsersRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUsersRespVo.ProtoReflect.Descriptor instead.
func (*RoleUsersRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{19}
}

func (x *RoleUsersRespVo) GetUsers() []*UserInfoRespVo {
	if x != nil {
		return x.Users
	}
	return nil
}

// 权限信息响应消息
type PermissionInfoRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // 权限ID
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // 权限名
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 权限描述
}

func (x *PermissionInfoRespVo) Reset() {
	*x = PermissionInfoRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionInfoRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfoRespVo) ProtoMessage() {}

func (x *PermissionInfoRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfoRespVo.ProtoReflect.Descriptor instead.
func (*PermissionInfoRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{20}
}

func (x *PermissionInfoRespVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionInfoRespVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionInfoRespVo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 角色权限响应消息
type RolePermissionRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId       int64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                   // 角色ID
	PermissionId int64 `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"` // 权限ID
}

func (x *RolePermissionRespVo) Reset() {
	*x = RolePermissionRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePermissionRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionRespVo) ProtoMessage() {}

func (x *RolePermissionRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionRespVo.ProtoReflect.Descriptor instead.
func (*RolePermissionRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{21}
}

func (x *RolePermissionRespVo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RolePermissionRespVo) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

// 角色权限列表响应消息
type RolePermissionsRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions []*PermissionInfoRespVo `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"` // 权限信息列表
}

func (x *RolePermissionsRespVo) Reset() {
	*x = RolePermissionsRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePermissionsRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsRespVo) ProtoMessage() {}

func (x *RolePermissionsRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsRespVo.ProtoReflect.Descriptor instead.
func (*RolePermissionsRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{22}
}

func (x *RolePermissionsRespVo) GetPermissions() []*PermissionInfoRespVo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// 权限角色列表响应消息
type PermissionRolesRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []*RoleInfoRespVo `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"` // 角色信息列表
}

func (x *PermissionRolesRespVo) Reset() {
	*x = PermissionRolesRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionRolesRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRolesRespVo) ProtoMessage() {}

func (x *PermissionRolesRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRolesRespVo.ProtoReflect.Descriptor instead.
func (*PermissionRolesRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{23}
}

func (x *PermissionRolesRespVo) GetRoles() []*RoleInfoRespVo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 空消息
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{24}
}

// 布尔值响应消息
type BoolRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BoolRespVo) Reset() {
	*x = BoolRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolRespVo) ProtoMessage() {}

func (x *BoolRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolRespVo.ProtoReflect.Descriptor instead.
func (*BoolRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{25}
}

func (x *BoolRespVo) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

var File_api_user_server_proto protoreflect.FileDescriptor

var file_api_user_server_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5e, 0x0a, 0x0f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12,
	0x19, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x45, 0x0a, 0x11,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x56,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x1d, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x56, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x0d, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x13,
	0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x56, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x23, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x57, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x5b,
	0x0a, 0x1a, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x56, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0x26, 0x0a, 0x0e, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x56, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x34, 0x0a, 0x0e, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x4e, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x42, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x56, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x31, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x56, 0x6f, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x44, 0x0a, 0x0f, 0x52, 0x6f,
	0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x31, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x22, 0x5c, 0x0a, 0x14, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x54,
	0x0a, 0x14, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x15, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x43, 0x0a,
	0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x56, 0x6f, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x15, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x31, 0x0a, 0x05, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x22, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xf1, 0x02, 0x0a, 0x0a,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a,
	0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x47, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x47, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x56,
	0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x44,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x56, 0x6f, 0x12, 0x49, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x32,
	0xa0, 0x02, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x47,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x43, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56,
	0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x42,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x56, 0x6f, 0x32, 0xc0, 0x02, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x10, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52,
	0x6f, 0x6c, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x56, 0x6f, 0x12, 0x4d, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x56,
	0x6f, 0x12, 0x48, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x48, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x56, 0x6f, 0x32, 0x98, 0x02, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x59, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x21, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f,
	0x12, 0x52, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56,
	0x6f, 0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x56, 0x6f, 0x12, 0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x21, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f,
	0x32, 0xd7, 0x03, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x5d, 0x0a, 0x16, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x20,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x56, 0x6f,
	0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x56, 0x6f, 0x12, 0x5f, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x56,
	0x6f, 0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x56, 0x6f, 0x12, 0x54, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x5a, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x56, 0x6f, 0x1a, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x52, 0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x65, 0x48, 0x61,
	0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56,
	0x6f, 0x1a, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x32, 0x68, 0x0a, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x55, 0x0a,
	0x11, 0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x17, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x56, 0x6f, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_user_server_proto_rawDescOnce sync.Once
	file_api_user_server_proto_rawDescData = file_api_user_server_proto_rawDesc
)

func file_api_user_server_proto_rawDescGZIP() []byte {
	file_api_user_server_proto_rawDescOnce.Do(func() {
		file_api_user_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_server_proto_rawDescData)
	})
	return file_api_user_server_proto_rawDescData
}

var file_api_user_server_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_user_server_proto_goTypes = []any{
	(*UserIdReqVo)(nil),                // 0: user_server.UserIdReqVo
	(*CreateUserReqVo)(nil),            // 1: user_server.CreateUserReqVo
	(*UpdateUserReqVo)(nil),            // 2: user_server.UpdateUserReqVo
	(*VerificationReqVo)(nil),          // 3: user_server.VerificationReqVo
	(*RoleIdReqVo)(nil),                // 4: user_server.RoleIdReqVo
	(*CreateRoleReqVo)(nil),            // 5: user_server.CreateRoleReqVo
	(*UserRoleReqVo)(nil),              // 6: user_server.UserRoleReqVo
	(*RolePermissionReqVo)(nil),        // 7: user_server.RolePermissionReqVo
	(*PermissionIdReqVo)(nil),          // 8: user_server.PermissionIdReqVo
	(*CreatePermissionReqVo)(nil),      // 9: user_server.CreatePermissionReqVo
	(*RoleIdPermissionIdReqVo)(nil),    // 10: user_server.RoleIdPermissionIdReqVo
	(*UserTokenPermissionIdReqVo)(nil), // 11: user_server.UserTokenPermissionIdReqVo
	(*PermissionNameReqVo)(nil),        // 12: user_server.PermissionNameReqVo
	(*UserInfoRespVo)(nil),             // 13: user_server.UserInfoRespVo
	(*JwtTokenRespVo)(nil),             // 14: user_server.JwtTokenRespVo
	(*RoleInfoRespVo)(nil),             // 15: user_server.RoleInfoRespVo
	(*RoleInfoListRespVo)(nil),         // 16: user_server.RoleInfoListRespVo
	(*UserRoleRespVo)(nil),             // 17: user_server.UserRoleRespVo
	(*UserRolesRespVo)(nil),            // 18: user_server.UserRolesRespVo
	(*RoleUsersRespVo)(nil),            // 19: user_server.RoleUsersRespVo
	(*PermissionInfoRespVo)(nil),       // 20: user_server.PermissionInfoRespVo
	(*RolePermissionRespVo)(nil),       // 21: user_server.RolePermissionRespVo
	(*RolePermissionsRespVo)(nil),      // 22: user_server.RolePermissionsRespVo
	(*PermissionRolesRespVo)(nil),      // 23: user_server.PermissionRolesRespVo
	(*Empty)(nil),                      // 24: user_server.Empty
	(*BoolRespVo)(nil),                 // 25: user_server.BoolRespVo
}
var file_api_user_server_proto_depIdxs = []int32{
	15, // 0: user_server.RoleInfoListRespVo.role_list:type_name -> user_server.RoleInfoRespVo
	15, // 1: user_server.UserRolesRespVo.roles:type_name -> user_server.RoleInfoRespVo
	13, // 2: user_server.RoleUsersRespVo.users:type_name -> user_server.UserInfoRespVo
	20, // 3: user_server.RolePermissionsRespVo.permissions:type_name -> user_server.PermissionInfoRespVo
	15, // 4: user_server.PermissionRolesRespVo.roles:type_name -> user_server.RoleInfoRespVo
	0,  // 5: user_server.UserServer.GetUser:input_type -> user_server.UserIdReqVo
	2,  // 6: user_server.UserServer.UpdateUser:input_type -> user_server.UpdateUserReqVo
	1,  // 7: user_server.UserServer.CreateUser:input_type -> user_server.CreateUserReqVo
	3,  // 8: user_server.UserServer.Login:input_type -> user_server.VerificationReqVo
	3,  // 9: user_server.UserServer.DeleteUser:input_type -> user_server.VerificationReqVo
	5,  // 10: user_server.RoleServer.CreateRole:input_type -> user_server.CreateRoleReqVo
	4,  // 11: user_server.RoleServer.GetRole:input_type -> user_server.RoleIdReqVo
	4,  // 12: user_server.RoleServer.DeleteRole:input_type -> user_server.RoleIdReqVo
	24, // 13: user_server.RoleServer.GetRoleList:input_type -> user_server.Empty
	6,  // 14: user_server.UserRoleServer.AssignRoleToUser:input_type -> user_server.UserRoleReqVo
	6,  // 15: user_server.UserRoleServer.RemoveRoleFromUser:input_type -> user_server.UserRoleReqVo
	0,  // 16: user_server.UserRoleServer.GetRolesByUser:input_type -> user_server.UserIdReqVo
	4,  // 17: user_server.UserRoleServer.GetUsersByRole:input_type -> user_server.RoleIdReqVo
	9,  // 18: user_server.Permissions.CreatePermission:input_type -> user_server.CreatePermissionReqVo
	8,  // 19: user_server.Permissions.GetPermission:input_type -> user_server.PermissionIdReqVo
	12, // 20: user_server.Permissions.GetPermissionByName:input_type -> user_server.PermissionNameReqVo
	7,  // 21: user_server.RolePermissions.AssignPermissionToRole:input_type -> user_server.RolePermissionReqVo
	7,  // 22: user_server.RolePermissions.RemovePermissionFromRole:input_type -> user_server.RolePermissionReqVo
	4,  // 23: user_server.RolePermissions.GetPermissionsByRole:input_type -> user_server.RoleIdReqVo
	8,  // 24: user_server.RolePermissions.GetRolesByPermission:input_type -> user_server.PermissionIdReqVo
	10, // 25: user_server.RolePermissions.RoleHasPermission:input_type -> user_server.RoleIdPermissionIdReqVo
	11, // 26: user_server.UserPermissions.UserHasPermission:input_type -> user_server.UserTokenPermissionIdReqVo
	13, // 27: user_server.UserServer.GetUser:output_type -> user_server.UserInfoRespVo
	14, // 28: user_server.UserServer.UpdateUser:output_type -> user_server.JwtTokenRespVo
	14, // 29: user_server.UserServer.CreateUser:output_type -> user_server.JwtTokenRespVo
	14, // 30: user_server.UserServer.Login:output_type -> user_server.JwtTokenRespVo
	14, // 31: user_server.UserServer.DeleteUser:output_type -> user_server.JwtTokenRespVo
	15, // 32: user_server.RoleServer.CreateRole:output_type -> user_server.RoleInfoRespVo
	15, // 33: user_server.RoleServer.GetRole:output_type -> user_server.RoleInfoRespVo
	15, // 34: user_server.RoleServer.DeleteRole:output_type -> user_server.RoleInfoRespVo
	16, // 35: user_server.RoleServer.GetRoleList:output_type -> user_server.RoleInfoListRespVo
	17, // 36: user_server.UserRoleServer.AssignRoleToUser:output_type -> user_server.UserRoleRespVo
	17, // 37: user_server.UserRoleServer.RemoveRoleFromUser:output_type -> user_server.UserRoleRespVo
	18, // 38: user_server.UserRoleServer.GetRolesByUser:output_type -> user_server.UserRolesRespVo
	19, // 39: user_server.UserRoleServer.GetUsersByRole:output_type -> user_server.RoleUsersRespVo
	20, // 40: user_server.Permissions.CreatePermission:output_type -> user_server.PermissionInfoRespVo
	20, // 41: user_server.Permissions.GetPermission:output_type -> user_server.PermissionInfoRespVo
	20, // 42: user_server.Permissions.GetPermissionByName:output_type -> user_server.PermissionInfoRespVo
	21, // 43: user_server.RolePermissions.AssignPermissionToRole:output_type -> user_server.RolePermissionRespVo
	21, // 44: user_server.RolePermissions.RemovePermissionFromRole:output_type -> user_server.RolePermissionRespVo
	22, // 45: user_server.RolePermissions.GetPermissionsByRole:output_type -> user_server.RolePermissionsRespVo
	23, // 46: user_server.RolePermissions.GetRolesByPermission:output_type -> user_server.PermissionRolesRespVo
	25, // 47: user_server.RolePermissions.RoleHasPermission:output_type -> user_server.BoolRespVo
	25, // 48: user_server.UserPermissions.UserHasPermission:output_type -> user_server.BoolRespVo
	27, // [27:49] is the sub-list for method output_type
	5,  // [5:27] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_user_server_proto_init() }
func file_api_user_server_proto_init() {
	if File_api_user_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_user_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserIdReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateUserReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateUserReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*VerificationReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RoleIdReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoleReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UserRoleReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RolePermissionReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*PermissionIdReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePermissionReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RoleIdPermissionIdReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UserTokenPermissionIdReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*PermissionNameReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*UserInfoRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*JwtTokenRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RoleInfoRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*RoleInfoListRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*UserRoleRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UserRolesRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*RoleUsersRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*PermissionInfoRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*RolePermissionRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*RolePermissionsRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*PermissionRolesRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*BoolRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_api_user_server_proto_goTypes,
		DependencyIndexes: file_api_user_server_proto_depIdxs,
		MessageInfos:      file_api_user_server_proto_msgTypes,
	}.Build()
	File_api_user_server_proto = out.File
	file_api_user_server_proto_rawDesc = nil
	file_api_user_server_proto_goTypes = nil
	file_api_user_server_proto_depIdxs = nil
}
