// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: api/user_server.proto

package user_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息
type UserIdReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户id Req
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserIdReqVo) Reset() {
	*x = UserIdReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIdReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdReqVo) ProtoMessage() {}

func (x *UserIdReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdReqVo.ProtoReflect.Descriptor instead.
func (*UserIdReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{0}
}

func (x *UserIdReqVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateUserReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 创建用户 Req
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CreateUserReqVo) Reset() {
	*x = CreateUserReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReqVo) ProtoMessage() {}

func (x *CreateUserReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReqVo.ProtoReflect.Descriptor instead.
func (*CreateUserReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReqVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserReqVo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReqVo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateUserReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 更新用户 Req
	NewName  string `protobuf:"bytes,1,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UpdateUserReqVo) Reset() {
	*x = UpdateUserReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReqVo) ProtoMessage() {}

func (x *UpdateUserReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReqVo.ProtoReflect.Descriptor instead.
func (*UpdateUserReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserReqVo) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *UpdateUserReqVo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserReqVo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerificationReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 验证 Req
	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *VerificationReqVo) Reset() {
	*x = VerificationReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationReqVo) ProtoMessage() {}

func (x *VerificationReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationReqVo.ProtoReflect.Descriptor instead.
func (*VerificationReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationReqVo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerificationReqVo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RoleIdReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 角色id Req
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RoleIdReqVo) Reset() {
	*x = RoleIdReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleIdReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleIdReqVo) ProtoMessage() {}

func (x *RoleIdReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleIdReqVo.ProtoReflect.Descriptor instead.
func (*RoleIdReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{4}
}

func (x *RoleIdReqVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateRoleReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 创建角色 Req
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateRoleReqVo) Reset() {
	*x = CreateRoleReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoleReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReqVo) ProtoMessage() {}

func (x *CreateRoleReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReqVo.ProtoReflect.Descriptor instead.
func (*CreateRoleReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoleReqVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserRoleReqVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户角色 Req
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId int64 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *UserRoleReqVo) Reset() {
	*x = UserRoleReqVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRoleReqVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleReqVo) ProtoMessage() {}

func (x *UserRoleReqVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleReqVo.ProtoReflect.Descriptor instead.
func (*UserRoleReqVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{6}
}

func (x *UserRoleReqVo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRoleReqVo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 响应消息
type UserInfoRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户信息 Resp
	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UserInfoRespVo) Reset() {
	*x = UserInfoRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRespVo) ProtoMessage() {}

func (x *UserInfoRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRespVo.ProtoReflect.Descriptor instead.
func (*UserInfoRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfoRespVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoRespVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoRespVo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type JwtTokenRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// token Resp
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JwtTokenRespVo) Reset() {
	*x = JwtTokenRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtTokenRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtTokenRespVo) ProtoMessage() {}

func (x *JwtTokenRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtTokenRespVo.ProtoReflect.Descriptor instead.
func (*JwtTokenRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{8}
}

func (x *JwtTokenRespVo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RoleInfoRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 角色信息 Resp
	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RoleInfoRespVo) Reset() {
	*x = RoleInfoRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfoRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfoRespVo) ProtoMessage() {}

func (x *RoleInfoRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfoRespVo.ProtoReflect.Descriptor instead.
func (*RoleInfoRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{9}
}

func (x *RoleInfoRespVo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfoRespVo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleInfoListRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 角色信息列表 Resp
	RoleList []*RoleInfoRespVo `protobuf:"bytes,1,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"`
}

func (x *RoleInfoListRespVo) Reset() {
	*x = RoleInfoListRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfoListRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfoListRespVo) ProtoMessage() {}

func (x *RoleInfoListRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfoListRespVo.ProtoReflect.Descriptor instead.
func (*RoleInfoListRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{10}
}

func (x *RoleInfoListRespVo) GetRoleList() []*RoleInfoRespVo {
	if x != nil {
		return x.RoleList
	}
	return nil
}

type UserRoleRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户角色 Resp
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId int64 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *UserRoleRespVo) Reset() {
	*x = UserRoleRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRoleRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleRespVo) ProtoMessage() {}

func (x *UserRoleRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleRespVo.ProtoReflect.Descriptor instead.
func (*UserRoleRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{11}
}

func (x *UserRoleRespVo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRoleRespVo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UserRolesRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户角色列表 Resp
	Roles []*RoleInfoRespVo `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *UserRolesRespVo) Reset() {
	*x = UserRolesRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRolesRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRolesRespVo) ProtoMessage() {}

func (x *UserRolesRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRolesRespVo.ProtoReflect.Descriptor instead.
func (*UserRolesRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{12}
}

func (x *UserRolesRespVo) GetRoles() []*RoleInfoRespVo {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RoleUsersRespVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 角色用户列表 Resp
	Users []*UserInfoRespVo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *RoleUsersRespVo) Reset() {
	*x = RoleUsersRespVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleUsersRespVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUsersRespVo) ProtoMessage() {}

func (x *RoleUsersRespVo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUsersRespVo.ProtoReflect.Descriptor instead.
func (*RoleUsersRespVo) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{13}
}

func (x *RoleUsersRespVo) GetUsers() []*UserInfoRespVo {
	if x != nil {
		return x.Users
	}
	return nil
}

// 空消息
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_user_server_proto_rawDescGZIP(), []int{14}
}

var File_api_user_server_proto protoreflect.FileDescriptor

var file_api_user_server_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5e, 0x0a, 0x0f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12,
	0x19, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x45, 0x0a, 0x11,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x56,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x1d, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x56, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x0d, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x0e,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x26, 0x0a, 0x0e, 0x4a, 0x77, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x34, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x56, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4e, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x38, 0x0a, 0x09,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x52, 0x08, 0x72, 0x6f,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x31, 0x0a,
	0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x22, 0x44, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x56, 0x6f, 0x12, 0x31, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x52,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32,
	0xf1, 0x02, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x40,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f,
	0x12, 0x47, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x77, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x47, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x56, 0x6f, 0x12, 0x44, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x49, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x56, 0x6f, 0x32, 0xa0, 0x02, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x47, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x40, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f,
	0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x43, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x56, 0x6f, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x32, 0xc0, 0x02, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x10, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x4d, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x56, 0x6f, 0x12, 0x48, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56,
	0x6f, 0x1a, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x12,
	0x48, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42, 0x79, 0x52, 0x6f, 0x6c,
	0x65, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x56, 0x6f, 0x1a, 0x1c, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x56, 0x6f, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_user_server_proto_rawDescOnce sync.Once
	file_api_user_server_proto_rawDescData = file_api_user_server_proto_rawDesc
)

func file_api_user_server_proto_rawDescGZIP() []byte {
	file_api_user_server_proto_rawDescOnce.Do(func() {
		file_api_user_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_server_proto_rawDescData)
	})
	return file_api_user_server_proto_rawDescData
}

var file_api_user_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_user_server_proto_goTypes = []any{
	(*UserIdReqVo)(nil),        // 0: user_server.UserIdReqVo
	(*CreateUserReqVo)(nil),    // 1: user_server.CreateUserReqVo
	(*UpdateUserReqVo)(nil),    // 2: user_server.UpdateUserReqVo
	(*VerificationReqVo)(nil),  // 3: user_server.VerificationReqVo
	(*RoleIdReqVo)(nil),        // 4: user_server.RoleIdReqVo
	(*CreateRoleReqVo)(nil),    // 5: user_server.CreateRoleReqVo
	(*UserRoleReqVo)(nil),      // 6: user_server.UserRoleReqVo
	(*UserInfoRespVo)(nil),     // 7: user_server.UserInfoRespVo
	(*JwtTokenRespVo)(nil),     // 8: user_server.JwtTokenRespVo
	(*RoleInfoRespVo)(nil),     // 9: user_server.RoleInfoRespVo
	(*RoleInfoListRespVo)(nil), // 10: user_server.RoleInfoListRespVo
	(*UserRoleRespVo)(nil),     // 11: user_server.UserRoleRespVo
	(*UserRolesRespVo)(nil),    // 12: user_server.UserRolesRespVo
	(*RoleUsersRespVo)(nil),    // 13: user_server.RoleUsersRespVo
	(*Empty)(nil),              // 14: user_server.Empty
}
var file_api_user_server_proto_depIdxs = []int32{
	9,  // 0: user_server.RoleInfoListRespVo.role_list:type_name -> user_server.RoleInfoRespVo
	9,  // 1: user_server.UserRolesRespVo.roles:type_name -> user_server.RoleInfoRespVo
	7,  // 2: user_server.RoleUsersRespVo.users:type_name -> user_server.UserInfoRespVo
	0,  // 3: user_server.UserServer.GetUser:input_type -> user_server.UserIdReqVo
	2,  // 4: user_server.UserServer.UpdateUser:input_type -> user_server.UpdateUserReqVo
	1,  // 5: user_server.UserServer.CreateUser:input_type -> user_server.CreateUserReqVo
	3,  // 6: user_server.UserServer.Login:input_type -> user_server.VerificationReqVo
	3,  // 7: user_server.UserServer.DeleteUser:input_type -> user_server.VerificationReqVo
	5,  // 8: user_server.RoleServer.CreateRole:input_type -> user_server.CreateRoleReqVo
	4,  // 9: user_server.RoleServer.GetRole:input_type -> user_server.RoleIdReqVo
	4,  // 10: user_server.RoleServer.DeleteRole:input_type -> user_server.RoleIdReqVo
	14, // 11: user_server.RoleServer.GetRoleList:input_type -> user_server.Empty
	6,  // 12: user_server.UserRoleServer.AssignRoleToUser:input_type -> user_server.UserRoleReqVo
	6,  // 13: user_server.UserRoleServer.RemoveRoleFromUser:input_type -> user_server.UserRoleReqVo
	0,  // 14: user_server.UserRoleServer.GetRolesByUser:input_type -> user_server.UserIdReqVo
	4,  // 15: user_server.UserRoleServer.GetUsersByRole:input_type -> user_server.RoleIdReqVo
	7,  // 16: user_server.UserServer.GetUser:output_type -> user_server.UserInfoRespVo
	8,  // 17: user_server.UserServer.UpdateUser:output_type -> user_server.JwtTokenRespVo
	8,  // 18: user_server.UserServer.CreateUser:output_type -> user_server.JwtTokenRespVo
	8,  // 19: user_server.UserServer.Login:output_type -> user_server.JwtTokenRespVo
	8,  // 20: user_server.UserServer.DeleteUser:output_type -> user_server.JwtTokenRespVo
	9,  // 21: user_server.RoleServer.CreateRole:output_type -> user_server.RoleInfoRespVo
	9,  // 22: user_server.RoleServer.GetRole:output_type -> user_server.RoleInfoRespVo
	9,  // 23: user_server.RoleServer.DeleteRole:output_type -> user_server.RoleInfoRespVo
	10, // 24: user_server.RoleServer.GetRoleList:output_type -> user_server.RoleInfoListRespVo
	11, // 25: user_server.UserRoleServer.AssignRoleToUser:output_type -> user_server.UserRoleRespVo
	11, // 26: user_server.UserRoleServer.RemoveRoleFromUser:output_type -> user_server.UserRoleRespVo
	12, // 27: user_server.UserRoleServer.GetRolesByUser:output_type -> user_server.UserRolesRespVo
	13, // 28: user_server.UserRoleServer.GetUsersByRole:output_type -> user_server.RoleUsersRespVo
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_user_server_proto_init() }
func file_api_user_server_proto_init() {
	if File_api_user_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_user_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserIdReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateUserReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateUserReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*VerificationReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RoleIdReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoleReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UserRoleReqVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UserInfoRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*JwtTokenRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RoleInfoRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RoleInfoListRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UserRoleRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*UserRolesRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RoleUsersRespVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_server_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_user_server_proto_goTypes,
		DependencyIndexes: file_api_user_server_proto_depIdxs,
		MessageInfos:      file_api_user_server_proto_msgTypes,
	}.Build()
	File_api_user_server_proto = out.File
	file_api_user_server_proto_rawDesc = nil
	file_api_user_server_proto_goTypes = nil
	file_api_user_server_proto_depIdxs = nil
}
