// Code generated by goctl. DO NOT EDIT.
// Source: user_server.proto

package server

import (
	"context"

	"user_server/internal/logic/permissions"
	"user_server/internal/svc"
	"user_server/user_server"
)

type PermissionsServer struct {
	svcCtx *svc.ServiceContext
	user_server.UnimplementedPermissionsServer
}

func NewPermissionsServer(svcCtx *svc.ServiceContext) *PermissionsServer {
	return &PermissionsServer{
		svcCtx: svcCtx,
	}
}

// 创建新权限
func (s *PermissionsServer) CreatePermission(ctx context.Context, in *user_server.CreatePermissionReqVo) (*user_server.PermissionInfoRespVo, error) {
	l := permissionslogic.NewCreatePermissionLogic(ctx, s.svcCtx)
	return l.CreatePermission(in)
}

// 获取权限信息
func (s *PermissionsServer) GetPermission(ctx context.Context, in *user_server.PermissionIdReqVo) (*user_server.PermissionInfoRespVo, error) {
	l := permissionslogic.NewGetPermissionLogic(ctx, s.svcCtx)
	return l.GetPermission(in)
}

// 从名称获取权限
func (s *PermissionsServer) GetPermissionByName(ctx context.Context, in *user_server.PermissionNameReqVo) (*user_server.PermissionInfoRespVo, error) {
	l := permissionslogic.NewGetPermissionByNameLogic(ctx, s.svcCtx)
	return l.GetPermissionByName(in)
}
