// Code generated by goctl. DO NOT EDIT.
// Source: user_server.proto

package rolepermissions

import (
	"context"

	"user_server/user_server"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolRespVo                 = user_server.BoolRespVo
	CreatePermissionReqVo      = user_server.CreatePermissionReqVo
	CreateRoleReqVo            = user_server.CreateRoleReqVo
	CreateUserReqVo            = user_server.CreateUserReqVo
	Empty                      = user_server.Empty
	JwtTokenRespVo             = user_server.JwtTokenRespVo
	PermissionIdReqVo          = user_server.PermissionIdReqVo
	PermissionInfoRespVo       = user_server.PermissionInfoRespVo
	PermissionNameReqVo        = user_server.PermissionNameReqVo
	PermissionRolesRespVo      = user_server.PermissionRolesRespVo
	RoleIdPermissionIdReqVo    = user_server.RoleIdPermissionIdReqVo
	RoleIdReqVo                = user_server.RoleIdReqVo
	RoleInfoListRespVo         = user_server.RoleInfoListRespVo
	RoleInfoRespVo             = user_server.RoleInfoRespVo
	RolePermissionReqVo        = user_server.RolePermissionReqVo
	RolePermissionRespVo       = user_server.RolePermissionRespVo
	RolePermissionsRespVo      = user_server.RolePermissionsRespVo
	RoleUsersRespVo            = user_server.RoleUsersRespVo
	UpdateUserReqVo            = user_server.UpdateUserReqVo
	UserIdReqVo                = user_server.UserIdReqVo
	UserInfoRespVo             = user_server.UserInfoRespVo
	UserRoleReqVo              = user_server.UserRoleReqVo
	UserRoleRespVo             = user_server.UserRoleRespVo
	UserRolesRespVo            = user_server.UserRolesRespVo
	UserTokenPermissionIdReqVo = user_server.UserTokenPermissionIdReqVo
	VerificationReqVo          = user_server.VerificationReqVo

	RolePermissions interface {
		// 分配权限给角色
		AssignPermissionToRole(ctx context.Context, in *RolePermissionReqVo, opts ...grpc.CallOption) (*RolePermissionRespVo, error)
		// 移除角色的权限
		RemovePermissionFromRole(ctx context.Context, in *RolePermissionReqVo, opts ...grpc.CallOption) (*RolePermissionRespVo, error)
		// 获取角色的权限
		GetPermissionsByRole(ctx context.Context, in *RoleIdReqVo, opts ...grpc.CallOption) (*RolePermissionsRespVo, error)
		// 获取具有某权限的角色
		GetRolesByPermission(ctx context.Context, in *PermissionIdReqVo, opts ...grpc.CallOption) (*PermissionRolesRespVo, error)
		// 检查角色是否具有某权限
		RoleHasPermission(ctx context.Context, in *RoleIdPermissionIdReqVo, opts ...grpc.CallOption) (*BoolRespVo, error)
	}

	defaultRolePermissions struct {
		cli zrpc.Client
	}
)

func NewRolePermissions(cli zrpc.Client) RolePermissions {
	return &defaultRolePermissions{
		cli: cli,
	}
}

// 分配权限给角色
func (m *defaultRolePermissions) AssignPermissionToRole(ctx context.Context, in *RolePermissionReqVo, opts ...grpc.CallOption) (*RolePermissionRespVo, error) {
	client := user_server.NewRolePermissionsClient(m.cli.Conn())
	return client.AssignPermissionToRole(ctx, in, opts...)
}

// 移除角色的权限
func (m *defaultRolePermissions) RemovePermissionFromRole(ctx context.Context, in *RolePermissionReqVo, opts ...grpc.CallOption) (*RolePermissionRespVo, error) {
	client := user_server.NewRolePermissionsClient(m.cli.Conn())
	return client.RemovePermissionFromRole(ctx, in, opts...)
}

// 获取角色的权限
func (m *defaultRolePermissions) GetPermissionsByRole(ctx context.Context, in *RoleIdReqVo, opts ...grpc.CallOption) (*RolePermissionsRespVo, error) {
	client := user_server.NewRolePermissionsClient(m.cli.Conn())
	return client.GetPermissionsByRole(ctx, in, opts...)
}

// 获取具有某权限的角色
func (m *defaultRolePermissions) GetRolesByPermission(ctx context.Context, in *PermissionIdReqVo, opts ...grpc.CallOption) (*PermissionRolesRespVo, error) {
	client := user_server.NewRolePermissionsClient(m.cli.Conn())
	return client.GetRolesByPermission(ctx, in, opts...)
}

// 检查角色是否具有某权限
func (m *defaultRolePermissions) RoleHasPermission(ctx context.Context, in *RoleIdPermissionIdReqVo, opts ...grpc.CallOption) (*BoolRespVo, error) {
	client := user_server.NewRolePermissionsClient(m.cli.Conn())
	return client.RoleHasPermission(ctx, in, opts...)
}
