// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	permissionsFieldNames          = builder.RawFieldNames(&Permissions{})
	permissionsRows                = strings.Join(permissionsFieldNames, ",")
	permissionsRowsExpectAutoSet   = strings.Join(stringx.Remove(permissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	permissionsRowsWithPlaceHolder = strings.Join(stringx.Remove(permissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserServerPermissionsIdPrefix   = "cache:userServer:permissions:id:"
	cacheUserServerPermissionsNamePrefix = "cache:userServer:permissions:name:"
)

type (
	permissionsModel interface {
		Insert(ctx context.Context, data *Permissions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Permissions, error)
		FindOneByName(ctx context.Context, name string) (*Permissions, error)
		Update(ctx context.Context, data *Permissions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPermissionsModel struct {
		sqlc.CachedConn
		table string
	}

	Permissions struct {
		Id          uint64         `db:"id"`
		CreatedAt   sql.NullTime   `db:"created_at"`
		UpdatedAt   sql.NullTime   `db:"updated_at"`
		DeletedAt   sql.NullTime   `db:"deleted_at"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		Status      string         `db:"status"`
	}
)

func newPermissionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPermissionsModel {
	return &defaultPermissionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`permissions`",
	}
}

func (m *defaultPermissionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userServerPermissionsIdKey := fmt.Sprintf("%s%v", cacheUserServerPermissionsIdPrefix, id)
	userServerPermissionsNameKey := fmt.Sprintf("%s%v", cacheUserServerPermissionsNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userServerPermissionsIdKey, userServerPermissionsNameKey)
	return err
}

func (m *defaultPermissionsModel) FindOne(ctx context.Context, id uint64) (*Permissions, error) {
	userServerPermissionsIdKey := fmt.Sprintf("%s%v", cacheUserServerPermissionsIdPrefix, id)
	var resp Permissions
	err := m.QueryRowCtx(ctx, &resp, userServerPermissionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionsModel) FindOneByName(ctx context.Context, name string) (*Permissions, error) {
	userServerPermissionsNameKey := fmt.Sprintf("%s%v", cacheUserServerPermissionsNamePrefix, name)
	var resp Permissions
	err := m.QueryRowIndexCtx(ctx, &resp, userServerPermissionsNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", permissionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionsModel) Insert(ctx context.Context, data *Permissions) (sql.Result, error) {
	userServerPermissionsIdKey := fmt.Sprintf("%s%v", cacheUserServerPermissionsIdPrefix, data.Id)
	userServerPermissionsNameKey := fmt.Sprintf("%s%v", cacheUserServerPermissionsNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, permissionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.Name, data.Description, data.Status)
	}, userServerPermissionsIdKey, userServerPermissionsNameKey)
	return ret, err
}

func (m *defaultPermissionsModel) Update(ctx context.Context, newData *Permissions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userServerPermissionsIdKey := fmt.Sprintf("%s%v", cacheUserServerPermissionsIdPrefix, data.Id)
	userServerPermissionsNameKey := fmt.Sprintf("%s%v", cacheUserServerPermissionsNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, permissionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeletedAt, newData.Name, newData.Description, newData.Status, newData.Id)
	}, userServerPermissionsIdKey, userServerPermissionsNameKey)
	return err
}

func (m *defaultPermissionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserServerPermissionsIdPrefix, primary)
}

func (m *defaultPermissionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPermissionsModel) tableName() string {
	return m.table
}
