// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRoleFieldNames          = builder.RawFieldNames(&UserRole{})
	userRoleRows                = strings.Join(userRoleFieldNames, ",")
	userRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(userRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(userRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserServerUserRoleIdPrefix           = "cache:userServer:userRole:id:"
	cacheUserServerUserRoleUserIdRoleIdPrefix = "cache:userServer:userRole:userId:roleId:"
)

type (
	userRoleModel interface {
		Insert(ctx context.Context, data *UserRole) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserRole, error)
		FindOneByUserIdRoleId(ctx context.Context, userId sql.NullInt64, roleId sql.NullInt64) (*UserRole, error)
		Update(ctx context.Context, data *UserRole) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserRoleModel struct {
		sqlc.CachedConn
		table string
	}

	UserRole struct {
		Id        uint64        `db:"id"`
		CreatedAt sql.NullTime  `db:"created_at"`
		UpdatedAt sql.NullTime  `db:"updated_at"`
		DeletedAt sql.NullTime  `db:"deleted_at"`
		UserId    sql.NullInt64 `db:"user_id"`
		RoleId    sql.NullInt64 `db:"role_id"`
	}
)

func newUserRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserRoleModel {
	return &defaultUserRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_role`",
	}
}

func (m *defaultUserRoleModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userServerUserRoleIdKey := fmt.Sprintf("%s%v", cacheUserServerUserRoleIdPrefix, id)
	userServerUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheUserServerUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userServerUserRoleIdKey, userServerUserRoleUserIdRoleIdKey)
	return err
}

func (m *defaultUserRoleModel) FindOne(ctx context.Context, id uint64) (*UserRole, error) {
	userServerUserRoleIdKey := fmt.Sprintf("%s%v", cacheUserServerUserRoleIdPrefix, id)
	var resp UserRole
	err := m.QueryRowCtx(ctx, &resp, userServerUserRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) FindOneByUserIdRoleId(ctx context.Context, userId sql.NullInt64, roleId sql.NullInt64) (*UserRole, error) {
	userServerUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheUserServerUserRoleUserIdRoleIdPrefix, userId, roleId)
	var resp UserRole
	err := m.QueryRowIndexCtx(ctx, &resp, userServerUserRoleUserIdRoleIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `role_id` = ? limit 1", userRoleRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, roleId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) Insert(ctx context.Context, data *UserRole) (sql.Result, error) {
	userServerUserRoleIdKey := fmt.Sprintf("%s%v", cacheUserServerUserRoleIdPrefix, data.Id)
	userServerUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheUserServerUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.RoleId)
	}, userServerUserRoleIdKey, userServerUserRoleUserIdRoleIdKey)
	return ret, err
}

func (m *defaultUserRoleModel) Update(ctx context.Context, newData *UserRole) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userServerUserRoleIdKey := fmt.Sprintf("%s%v", cacheUserServerUserRoleIdPrefix, data.Id)
	userServerUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheUserServerUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeletedAt, newData.UserId, newData.RoleId, newData.Id)
	}, userServerUserRoleIdKey, userServerUserRoleUserIdRoleIdKey)
	return err
}

func (m *defaultUserRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserServerUserRoleIdPrefix, primary)
}

func (m *defaultUserRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserRoleModel) tableName() string {
	return m.table
}
