// Code generated by goctl. DO NOT EDIT.
// Source: user_server.proto

package server

import (
	"context"

	"user_server/internal/logic/userpermissions"
	"user_server/internal/svc"
	"user_server/user_server"
)

type UserPermissionsServer struct {
	svcCtx *svc.ServiceContext
	user_server.UnimplementedUserPermissionsServer
}

func NewUserPermissionsServer(svcCtx *svc.ServiceContext) *UserPermissionsServer {
	return &UserPermissionsServer{
		svcCtx: svcCtx,
	}
}

// 检查用户是否具有某权限
func (s *UserPermissionsServer) UserHasPermission(ctx context.Context, in *user_server.UserTokenPermissionIdReqVo) (*user_server.BoolRespVo, error) {
	l := userpermissionslogic.NewUserHasPermissionLogic(ctx, s.svcCtx)
	return l.UserHasPermission(in)
}
