// Code generated by goctl. DO NOT EDIT.
// Source: user_server.proto

package userserver

import (
	"context"

	"user_server/user_server"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRoleReqVo    = user_server.CreateRoleReqVo
	CreateUserReqVo    = user_server.CreateUserReqVo
	Empty              = user_server.Empty
	JwtTokenRespVo     = user_server.JwtTokenRespVo
	RoleIdReqVo        = user_server.RoleIdReqVo
	RoleInfoListRespVo = user_server.RoleInfoListRespVo
	RoleInfoRespVo     = user_server.RoleInfoRespVo
	RoleUsersRespVo    = user_server.RoleUsersRespVo
	UpdateUserReqVo    = user_server.UpdateUserReqVo
	UserIdReqVo        = user_server.UserIdReqVo
	UserInfoRespVo     = user_server.UserInfoRespVo
	UserRoleReqVo      = user_server.UserRoleReqVo
	UserRoleRespVo     = user_server.UserRoleRespVo
	UserRolesRespVo    = user_server.UserRolesRespVo
	VerificationReqVo  = user_server.VerificationReqVo

	UserServer interface {
		GetUser(ctx context.Context, in *UserIdReqVo, opts ...grpc.CallOption) (*UserInfoRespVo, error)
		UpdateUser(ctx context.Context, in *UpdateUserReqVo, opts ...grpc.CallOption) (*JwtTokenRespVo, error)
		CreateUser(ctx context.Context, in *CreateUserReqVo, opts ...grpc.CallOption) (*JwtTokenRespVo, error)
		Login(ctx context.Context, in *VerificationReqVo, opts ...grpc.CallOption) (*JwtTokenRespVo, error)
		DeleteUser(ctx context.Context, in *VerificationReqVo, opts ...grpc.CallOption) (*JwtTokenRespVo, error)
	}

	defaultUserServer struct {
		cli zrpc.Client
	}
)

func NewUserServer(cli zrpc.Client) UserServer {
	return &defaultUserServer{
		cli: cli,
	}
}

func (m *defaultUserServer) GetUser(ctx context.Context, in *UserIdReqVo, opts ...grpc.CallOption) (*UserInfoRespVo, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUserServer) UpdateUser(ctx context.Context, in *UpdateUserReqVo, opts ...grpc.CallOption) (*JwtTokenRespVo, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUserServer) CreateUser(ctx context.Context, in *CreateUserReqVo, opts ...grpc.CallOption) (*JwtTokenRespVo, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUserServer) Login(ctx context.Context, in *VerificationReqVo, opts ...grpc.CallOption) (*JwtTokenRespVo, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserServer) DeleteUser(ctx context.Context, in *VerificationReqVo, opts ...grpc.CallOption) (*JwtTokenRespVo, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}
